"""xreated the chat table

Revision ID: 08e6fafbd1d4
Revises: d3adf2c93ef8
Create Date: 2026-09-07 02:30:01.535347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08e6fafbd1d4'
down_revision: Union[str, Sequence[str], None] = 'd3adf2c93ef8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts')
    op.create_index('ix_messages_recipient_sender', 'chat', ['reciever_id', 'sender_id'], unique=False)
    op.create_index('ix_messages_sender__recipient', 'chat', ['sender_id', 'reciever_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_sender__recipient', table_name='chat')
    op.drop_index('ix_messages_recipient_sender', table_name='chat')
    op.create_table('contacts',
    sa.Column('contact_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('contacts_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contact_id', name=op.f('contacts_pkey')),
    sa.UniqueConstraint('email', name=op.f('contacts_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
